"""
Main entrypoint for the CBAM reporting backend.

This FastAPI application exposes endpoints to generate CBAM compliant reports
for a given reporting period. Clients can submit basic product information
along with direct and indirect emissions per tonne to produce a populated
Excel template and a summarised PDF report. Generated files are saved
under the ``reports`` directory inside the container and the API returns
the relative paths so that a front‑end can download them.

The implementation intentionally keeps the data model simple for an MVP.
Future iterations can expand the models to include additional CBAM fields
(facility address, country, scope breakdown, supporting documents, etc.).

To start the application locally via Docker, run ``docker compose up --build``
from the repository root. The service will be available on port 8088 and
serving the API at ``/docs`` will show the autogenerated OpenAPI UI.
"""

from __future__ import annotations

import os
import uuid
from typing import List

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from cbam_excel import generate_excel_report
from cbam_pdf import generate_pdf_report


app = FastAPI(title="ISOTEC CBAM Reporting API", version="0.1.0")


class Product(BaseModel):
    """Representation of a single product entry in a CBAM report.

    Attributes:
        cn_code: CN code of the product (for example "7604" for aluminium profiles).
        name: Human readable name of the product.
        production_ton: Amount of product produced during the reporting period in tonnes.
        direct_see: Direct specific embedded emissions (tCO2e per tonne).
        indirect_see: Indirect specific embedded emissions (tCO2e per tonne).
    """

    cn_code: str = Field(..., example="7604")
    name: str = Field(..., example="Alüminyum Profil")
    production_ton: float = Field(..., gt=0, example=100.0)
    direct_see: float = Field(..., ge=0, example=0.5)
    indirect_see: float = Field(..., ge=0, example=1.2)

    @property
    def total_see(self) -> float:
        """Calculate total specific embedded emissions.

        Returns:
            Sum of direct and indirect SEE values.
        """
        return self.direct_see + self.indirect_see


class ReportRequest(BaseModel):
    """Request body for creating a CBAM report.

    Attributes:
        quarter: Reporting period identifier (e.g. "2025-Q3").
        products: List of products included in the report.
    """

    quarter: str = Field(..., pattern=r"^\d{4}-Q[1-4]$", example="2025-Q3")
    products: List[Product]


class ReportResponse(BaseModel):
    """Response returned after generating a report."""

    report_id: str
    excel: str
    pdf: str


@app.post("/reports", response_model=ReportResponse)
async def create_report(report: ReportRequest) -> ReportResponse:
    """Generate an Excel and PDF report from the provided data.

    A unique identifier is generated for each report. The Excel template is
    populated with the submitted product data and saved under ``reports/<uuid>.xlsx``.
    A simple PDF summary is generated and saved as ``reports/<uuid>.pdf``.

    Args:
        report: Report request payload containing the reporting period and
            product information.

    Returns:
        ReportResponse: Contains the unique report ID and relative file paths
        of the generated Excel and PDF files.
    """
    if not report.products:
        raise HTTPException(status_code=400, detail="At least one product is required")

    # Create a unique report identifier and ensure report directory exists
    report_id = str(uuid.uuid4())
    reports_dir = os.path.join(os.getcwd(), "reports")
    os.makedirs(reports_dir, exist_ok=True)

    excel_filename = f"{report_id}.xlsx"
    pdf_filename = f"{report_id}.pdf"
    excel_path = os.path.join(reports_dir, excel_filename)
    pdf_path = os.path.join(reports_dir, pdf_filename)

    # Generate Excel using the template
    generate_excel_report(report, excel_path)

    # Generate PDF summary
    generate_pdf_report(report, pdf_path)

    return ReportResponse(
        report_id=report_id,
        excel=f"/reports/{excel_filename}",
        pdf=f"/reports/{pdf_filename}",
    )